### ISSUE TITLE
'Hazelcast instance is not active' during CamelContext shutdown

### ISSUE THREAD

**Issue by nhoughto** [mpilone/hazelcastmq#4]
I've got my hazelcastmq + camel integration working quite well, when trying to do a graceful shutdown sending a SIGINT to the running java process and calling .stop() on the camel context via Java's addShutdownHook(), hazelcastmq has trouble with trying to stop listeners etc here is the stack:

```
2014-08-15 02:28:54:545 WARN  org.apache.camel.impl.DefaultShutdownStrategy  - Error occurred while shutting down route: Consumer[hazelcastmq://queue:blah?concurrentConsumers=25]. This exception will be ignored.
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
    at com.hazelcast.spi.AbstractDistributedObject.getService(AbstractDistributedObject.java:78)
    at com.hazelcast.queue.proxy.QueueProxySupport.removeItemListener(QueueProxySupport.java:191)
    at com.hazelcast.queue.proxy.QueueProxyImpl.removeItemListener(QueueProxyImpl.java:34)
    at org.mpilone.hazelcastmq.core.DefaultHazelcastMQConsumer$HzQueueListener.shutdown(DefaultHazelcastMQConsumer.java:400)
    at org.mpilone.hazelcastmq.core.DefaultHazelcastMQConsumer.stop(DefaultHazelcastMQConsumer.java:230)
    at org.mpilone.hazelcastmq.core.DefaultHazelcastMQContext.stop(DefaultHazelcastMQContext.java:244)
    at org.mpilone.hazelcastmq.camel.HazelcastMQCamelConsumer$SingleThreadedConsumer.stop(HazelcastMQCamelConsumer.java:118)
    at org.mpilone.hazelcastmq.camel.HazelcastMQCamelConsumer.doStop(HazelcastMQCamelConsumer.java:69)
    at org.apache.camel.support.ServiceSupport.stop(ServiceSupport.java:102)
    at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:141)
    at org.apache.camel.impl.DefaultShutdownStrategy.shutdownNow(DefaultShutdownStrategy.java:336)
    at org.apache.camel.impl.DefaultShutdownStrategy$ShutdownTask.run(DefaultShutdownStrategy.java:609)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Looks like its trying to stop listening to stuff, but hazelcast has already been stopped?

**Comment by bwzhang2011** [comment]
@mpilone, how does this going on ? in my production environment, with hz3.3.5 (the last version in hz3.3.x) hazelcastInstanceNotActiveException still exists except for network switching for a long time and everything goes fine currently. next month we would upgrade to hz3.4.1 or hz3.5 snapshot for testing.
